# Load from a joblib model and use it to classify

In [2]:
import joblib   
clf = joblib.load("models/iris_classifier.joblib")

In [6]:
import pandas as pd

sample_test_data = pd.DataFrame(
    [{"SepalLengthCm": 6.1, "SepalWidthCm": 2.8,"PetalLengthCm": 4.3, "PetalWidthCm": 1.3}]
    )
sample_test_data

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            6.1           2.8            4.3           1.3

In [7]:
clf.predict(sample_test_data)

array(['Iris-versicolor'], dtype=object)

# Testing Irisinput

In [9]:
from data_processing import IrisInput

payload = IrisInput(
    SepalLengthCm = 6.1, 
    SepalWidthCm= 2.8,
    PetalLengthCm= 4.3, 
    PetalWidthCm= 1.3
    )
payload

IrisInput(SepalLengthCm=6.1, SepalWidthCm=2.8, PetalLengthCm=4.3, PetalWidthCm=1.3)

In [10]:
payload.model_dump()  #gör om den till en dictionary

{'SepalLengthCm': 6.1,
 'SepalWidthCm': 2.8,
 'PetalLengthCm': 4.3,
 'PetalWidthCm': 1.3}

In [12]:
pd.DataFrame([payload.model_dump()])  #gör om den till en pandas dataframe, men det måste vara en lista av dictionaries

# Pandas måste ha en dictionary i en lista, annars blir det fel.

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            6.1           2.8            4.3           1.3

# Testing a post request in Python

In [15]:
import requests

url = "http://127.0.0.1:8000/api/predict"
payload ={
  "SepalLengthCm": 6.1,
  "SepalWidthCm": 2.8,
  "PetalLengthCm": 4.3,
  "PetalWidthCm": 1.3
}
response = requests.post(url, json=payload)
response

In [18]:
response.json()

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [ ]:
requests.get(url = "http://127.0.0.1:8000/api/")
pd.DataFrame(response.json())